spring.application.name=citologi

spring.datasource.url=jdbc:postgresql://localhost:5432/citologi_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

vaadin.launch-browser=true

logging.level.org.springframework.security=DEBUG
